# 服务名称
spring:
  application:
    name: lvsiqi-spring-cloud-eureka
# 服务端口号
server:
  port: 8080

#Eureka 相关配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
    # 是否从其他的服务中心同步服务列表
    fetch-registry: false
    # 是否把自己作为服务注册到其他服务注册中心
    register-with-eureka: false


